### ISSUE TITLE
Failed with jsonrpcclient 4.x

### ISSUE THREAD

**Issue by Revolution1** [deepgully/pyzil#13]
In a brand new virtualenv

`/tmp $ virtualenv testpyzil`

```
created virtual environment CPython3.9.9.final.0-64 in 688ms
  creator CPython3Posix(dest=/private/tmp/testpyzil, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/revol/Library/Application Support/virtualenv)
    added seed packages: pip==22.0.3, setuptools==60.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
```

`/tmp $ source testpyzil/bin/activate`

`/tmp [testpyzil] $ pip freeze`
```
# NO PACKAGE
```

`/tmp [testpyzil] $ pip install pyzil`
```
...
Collecting jsonrpcclient[requests]
  Using cached jsonrpcclient-4.0.2-py3-none-any.whl         <------ auto selected latest version
...
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.12 eth-hash-0.3.2 fastecdsa-2.2.3 idna-3.3 jsonrpcclient-4.0.2 protobuf-3.19.4 pycryptodome-3.14.1 pyethash-0.1.27 pyzil-1.5.22 requests-2.27.1 urllib3-1.26.8
```

`/tmp [testpyzil] $ python -c "from pyzil.zilliqa import chain"`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/testpyzil/lib/python3.9/site-packages/pyzil/zilliqa/chain.py", line 21, in <module>
    from pyzil.zilliqa.api import ZilliqaAPI, APIError
  File "/private/tmp/testpyzil/lib/python3.9/site-packages/pyzil/zilliqa/api.py", line 15, in <module>
    from jsonrpcclient.exceptions import JsonRpcClientError
ModuleNotFoundError: No module named 'jsonrpcclient.exceptions'
```

**Comment by Revolution1** [comment]
Need:
Fix `install_requires` versions in `setup.py`
or
Change code to adapt jsonrpcclient 4.x

**Comment by hamdi-99** [comment]
isn't there any fix for this issue yet ?
